### ISSUE TITLE
Structure of the style guide

### ISSUE THREAD

**Issue by bbatsov** [rubocop-hq/packaging-style-guide#2]
While working on publishing the guide I noticed that its structure is centered around the cops in the `rubocop-packaging` extension, which is a bit different from the typical style guide structure we employ, that tends to focus on the guidelines and their rationale and mentions RuboCop only as a tool that can help with the adoption of those practices. 

Generally, I feel it's best to put cop documentation in the extension docs (e.g. https://docs.rubocop.org/rubocop-rspec/cops.html), instead of the style guide.

**Comment by utkarsh2102** [comment]
Hi @bbatsov,

You're right! I'll migrate that to the extension docs instead!
Can we also get something like https://docs.rubocop.org/rubocop-packaging? 😄

**Comment by utkarsh2102** [comment]
A gentle ping on this^ :)
Anything I can do from my end? We already do have the `docs/` directory which just needs to be hosted. Let me know if I can do something to get this hosted or any other alternative that we can adapt  😄

**Comment by bbatsov** [comment]
See https://docs.rubocop.org/rubocop-packaging/index.html

**Comment by utkarsh2102** [comment]
Wow, aren't you the best?  ❤️ 
Many thanks! I'll fix the docs and migrate the explanation, et al, from style-guide to those docs!

Really, thank you so much! 😭 ❤️

**Comment by bbatsov** [comment]
You're welcome!
